services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sonarr radarr jellyseerr bazarr qbittorrent jellyfin --debug --cleanup --remove-volumes
    restart: always
